on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-syscall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - name: Check formatting
        working-directory: syscall
        run: cargo fmt --all -- --check
      - name: Check clippy
        working-directory: syscall
        run: cargo clippy -- -D warnings

  check-nosc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - name: Check formatting
        working-directory: nosc
        run: cargo fmt --all -- --check
      - name: Check clippy
        working-directory: nosc
        run: cargo clippy -- -D warnings
