on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-systemcalls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - name: Check formatting
        working-directory: systemcalls
        run: cargo fmt --all -- --check
      - name: Check clippy
        working-directory: systemcalls
        run: cargo clippy -- -D warnings

  check-nosc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy, rust-src
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check clippy
        run: cargo clippy -- -D warnings
